EmployeeManagmentSystem/Controllers/DepartmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DataAccess;

namespace EmployeeManagmentSystem.Controllers
{
    public class DepartmentController : Controller
    {
        //
        // GET: /Department/
        public EMS db = new EMS();


        public ActionResult Index()
        {
            var efData = db.tblDepartments.Where(x => x.IsActive == true).ToList();

            return View(efData);
        }

        public ActionResult Save(string deptName, int deptId)
        {
            var efData = db.tblDepartments.Where(x => x.Id == deptId).FirstOrDefault();
            var data = db.tblDepartments.Where(x => x.Name.ToLower() == deptName.ToLower() && x.IsActive==true).FirstOrDefault();

            if (data == null)
            {
                if (efData == null)
                {
                    efData = new tblDepartment();
                    db.tblDepartments.Add(efData);
                }
                efData.Id = deptId;
                efData.Name = deptName;
                efData.IsActive = true;
                db.SaveChanges();
                return Json("Ok");
            }
            else
            {

                return Json("Error");
            }

        }

        public ActionResult Delete(int deptId)
        {
            var efData = db.tblDepartments.Where(x => x.Id == deptId).FirstOrDefault();
            var efEmpData = db.tblEmployees.Where(x => x.DeptId == deptId &&x.IsActive==true).FirstOrDefault();

            if (efEmpData == null)
            {
                efData.IsActive = false;
                db.SaveChanges();
                return Json("Ok");

            }
            else
            {
                return Json("Error");
            }
        }

        public ActionResult GetDataById(int deptId)
        {
            tblDepartment mDepartment = new tblDepartment();
            var efData = db.tblDepartments.Where(x => x.Id == deptId).FirstOrDefault();
            if (efData != null)
            {
                mDepartment.Name = efData.Name;
                mDepartment.Id = efData.Id;
            }
            return Json(mDepartment);
        }


    }
}

EmployeeManagmentSystem/Controllers/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DataAccess;
using Model;

namespace EmployeeManagmentSystem.Controllers
{
    public class EmployeeController : Controller
    {
        //
        // GET: /Employee/

        public EMS db = new EMS();

        public ActionResult Index()
        {
            var efData = (from dept in db.tblDepartments
                          join emp in db.tblEmployees
                              on dept.Id equals emp.DeptId
                          where emp.IsActive == true
                          select new Employee
                          {
                              Id = emp.Id,
                              Name = emp.Name,
                              Surname = emp.Surname,
                              DepartmentName = dept.Name,
                              Address = emp.Address,
                              Qualification =emp.Qualification,
                              ContactNumber=emp.ContactNumber,
                          }).ToList();

            return View(efData);
        }

        public ActionResult Add(int id=0)
        {
            ViewBag.id = id;
            return View();

        }
        public ActionResult Save(Employee mEmployee)
        {
            var efData = db.tblEmployees.Where(x => x.Id == mEmployee.Id).FirstOrDefault();
            if (efData == null)
            {
                efData = new tblEmployee();
                db.tblEmployees.Add(efData);
            }
            efData.Id = mEmployee.Id;
            efData.Name = mEmployee.Name;
            efData.Surname = mEmployee.Surname;
            efData.DeptId = mEmployee.DeptId;
            efData.Address = mEmployee.Address;
            efData.Qualification = mEmployee.Qualification;
            efData.ContactNumber = mEmployee.ContactNumber;

            efData.IsActive = true;
            db.SaveChanges();
            return Json("Ok");
        }

        public ActionResult GetAllDepartment()
        {
            var efData = db.tblDepartments.Where(x => x.IsActive == true).ToList();
            return Json(efData);
        }

        public ActionResult Delete(int empId)
        {
            var efData = db.tblEmployees.Where(x => x.Id == empId).FirstOrDefault();
            if (efData != null)
            {
                efData.IsActive = false;
                db.SaveChanges();
            }
            return Json("Ok");
        }

        public ActionResult GetDataById(int empId)
        {
            tblEmployee mEmployee = new tblEmployee();
            var efData = db.tblEmployees.Where(x => x.Id == empId).FirstOrDefault();
            if (efData != null)
            {
                mEmployee.Name = efData.Name;
                mEmployee.Id = efData.Id;
                mEmployee.Surname = efData.Surname;
                mEmployee.DeptId = efData.DeptId;
                mEmployee.Address = efData.Address;
                mEmployee.Qualification = efData.Qualification;
                mEmployee.ContactNumber = efData.ContactNumber;

            }
            return Json(mEmployee);
        }

    }
}

EmployeeManagmentSystem/Views/Department/Index.cshtml
@model List<DataAccess.tblDepartment>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MasterPage.cshtml";
}

<div class="container">
    <div class="row">
        <div class="col-sm-4">
            <div class="form-group">
                <label for="usr">Department Name:</label>
                <input type="text" class="form-control" id="txtDeptName" required>
            </div>
        </div>
        <div class="col-sm-2">
            <div class="form-group pull-right">
                <a href="#" class="btn btn-success" style="margin-top: 23px;" id="btnSave">Save</a>
            </div>
        </div>
    </div>
    <input type="hidden" id="hdnId" value="0" />
    <div class="row">
        <table class="table table-bordered table-responsive">
            <thead>
                <tr>
                    <th>Department Name</th>
                    <th style="text-align: center;">Edit</th>
                    <th style="text-align: center;">Delete</th>


                </tr>
            </thead>
            <tbody>
                @if (Model.Count != 0)
                {
                    foreach (var item in Model)
                    {
                    <tr>
                        <td>@item.Name</td>
                        <td style="text-align: center;"><a href="#" onclick="fnGetDataById(@item.Id)"><i class="fa fa-pencil"></i></a></td>
                        <td style="text-align: center;"><a href="#" onclick="fnDeleteById(@item.Id)"><i class="fa fa-trash" aria-hidden="true"></i></a></td>

                    </tr>
                    }
                }
                else
                {
                    <tr>
                        <td colspan="3" style="text-align: center;">No Data Available</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

<script>
    $(document).ready(function () {

        $("#btnSave").click(function () {
            if (validation() == true) {
                $.ajax({
                    url: '/Department/Save',
                    type: "POST",
                    contentType: "application/json; charset=utf-8",

                    data: "{'deptName': '" + $("#txtDeptName").val() + "','deptId': '" + $("#hdnId").val() + "'}",
                    success: function (result) {
                        if (result == "Ok") {
                            alert("Data Save Successfully..!!");
                            window.location.href = "@Url.Action("Index", "Department")"
                        }
                        else {
                            alert("Department is already exists..!!");
                            $("#txtDeptName").val('');
                        }
                    },
                    error: function (err) {
                        alert(err.statusText);
                    }
                });


            }
            else {
                alert("Please enter data..!!");
            }

        });

    });

    function validation() {

        var isValid = true;

        if ($("#txtDeptName").val().length == 0) {
            $("#txtDeptName").css('border-color', 'red');
            isValid = false;
        }
        return isValid;

    }

    function fnGetDataById(id) {
        $.ajax({
            url: '/Department/GetDataById',
            type: "POST",
            data: '{deptId:"' + id + '"}',
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            success: function (response) {
                $.each(response, function (index, element) {
                    $("#txtDeptName").val(response.Name);
                    $("#hdnId").val(response.Id);

                });

            },
            error: function (err) {
                alert(err.statusText);
            }
        });

    }
    function fnDeleteById(id) {

        if (confirm("Do you want to delete this record?")) {
            $.ajax({
                url: '/Department/Delete',
                type: "POST",
                contentType: "application/json; charset=utf-8",

                data: "{'deptId': '" + id + "'}",
                success: function (result) {
                    if (result == "Ok") {
                        window.location.href = "@Url.Action("Index", "Department")"
                    }
                    else {
                        alert("Data is already in used in another table ,So you cannot delete it..!!");
                    }
                },
                error: function (err) {
                    alert(err.statusText);
                }
            });
        }

    }
</script>

EmployeeManagmentSystem/Views/Employee/Add.cshtml
@{
    ViewBag.Title = "Add";
    Layout = "~/Views/Shared/_MasterPage.cshtml";
}


<style>
    label {
        font-size: 16px !important;
    }

    btn {
        font-size: 18px !important;
    }
</style>


<div class="container">
    <div class="row">
        <div class="col-sm-4">
            <div class="form-group">
                <label for="usr">Department Name:</label>
                <div class="form-group">
                    <select id="drpDeptName" class="form-control">
                    </select>
                </div>
            </div>
        </div>
        <div class="col-sm-4">
            <div class="form-group">
                <label for="usr">Name:</label>
                <input type="text" class="form-control" id="txtName">
            </div>
        </div>
        <div class="col-sm-4">
            <div class="form-group">
                <label for="usr">SurName:</label>
                <input type="text" class="form-control" id="txtSurName">
            </div>
        </div>
        <div class="col-sm-6">
            <div class="form-group">
                <label for="usr">ContactNumber:</label>
                <input type="text" class="form-control" id="txtContact" maxlength="10">
            </div>
        </div>
        <div class="col-sm-6">
            <div class="form-group">
                <label for="usr">Qualification:</label>
                <input type="text" class="form-control" id="txtQualification">
            </div>
        </div>
        <div class="col-sm-12">
            <div class="form-group">
                <label for="usr">Address:</label>
                <textarea id="txtAddress" class="form-control" rows="4"></textarea>
            </div>
        </div>
        <div class="col-sm-12">
            <div class="form-group ">
                <a href="#" class="btn btn-success" style="margin-top: 23px;" id="btnSave">Save</a>

                <a href="@Url.Action("Index", "Employee")" class="btn btn-warning" style="margin-top: 23px;" >Back To List</a>
            </div>
        </div>
    </div>
    <input type="hidden" id="hdnId" value="0" />
</div>

<script>
    $(document).ready(function () {


        $("#txtContact").keydown(function (e) {
            // Allow: backspace, delete, tab, escape, enter and .
            if ($.inArray(e.keyCode, [46, 8, 9, 27, 13, 110, 190]) !== -1 ||
                // Allow: Ctrl+A, Command+A
                (e.keyCode === 65 && (e.ctrlKey === true || e.metaKey === true)) ||
                // Allow: home, end, left, right, down, up
                (e.keyCode >= 35 && e.keyCode <= 40)) {
                // let it happen, don't do anything
                return;
            }
            // Ensure that it is a number and stop the keypress
            if ((e.shiftKey || (e.keyCode < 48 || e.keyCode > 57)) && (e.keyCode < 96 || e.keyCode > 105)) {
                e.preventDefault();
            }
        });


            fnGetAllDepartment();
            var empId = '@ViewBag.id'

        fnGetDataById(empId);

        $("#btnSave").click(function () {
            debugger;
            if (validation() == true) {
                var mEmployee = {};
                mEmployee.Id = $("#hdnId").val();
                mEmployee.Name = $("#txtName").val();
                mEmployee.Surname = $("#txtSurName").val();
                mEmployee.DeptId = $("#drpDeptName").val();
                mEmployee.Address = $("#txtAddress").val();
                mEmployee.ContactNumber = $("#txtContact").val();
                mEmployee.Qualification = $("#txtQualification").val();



                $.ajax({
                    url: '/Employee/Save',
                    type: "POST",
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify(mEmployee),
                    dataType: "json",

                    success: function (result) {
                        if (result == "Ok") {
                            window.location.href = "@Url.Action("Index", "Employee")"
                        }
                    },
                    error: function (err) {
                        alert(err.statusText);
                    }
                });


            }
            else {
            }

        });

        });



        function validation() {

            var isValid = true;

            if ($("#txtName").val().length == 0) {
                $("#txtName").css('border-color', 'red');
                isValid = false;
            }
            if ($("#txtSurName").val().length == 0) {
                $("#txtSurName").css('border-color', 'red');
                isValid = false;
            }

            if ($("#txtAddress").val().length == 0) {
                $("#txtAddress").css('border-color', 'red');
                isValid = false;
            }

            if ($("#txtContact").val().length == 0) {
                $("#txtContact").css('border-color', 'red');
                isValid = false;
            }
            if ($("#txtContact").val().length != 10) {
                $("#txtContact").css('border-color', 'red');
                alert("Enter valid mobile number");
                isValid = false;
            }

            if ($("#txtQualification").val().length == 0) {
                $("#txtQualification").css('border-color', 'red');
                isValid = false;
            }

            if ($("#drpDeptName").val() == 0) {
                $("#drpDeptName").css('border-color', 'red');
                isValid = false;
            }

           

            return isValid;

        }

        function fnGetDataById(empId) {
            $.ajax({
                url: '/Employee/GetDataById',
                type: "POST",
                data: '{empId:"' + empId + '"}',
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                success: function (response) {
                    $.each(response, function (index, element) {
                        $("#txtName").val(response.Name);
                        $("#txtSurName").val(response.Surname);
                        $("#drpDeptName").val(response.DeptId);
                        $("#txtAddress").val(response.Address);
                        $("#txtContact").val(response.ContactNumber);
                        $("#txtQualification").val(response.Qualification);

                        $("#hdnId").val(response.Id);

                    });

                },
                error: function (err) {
                    alert(err.statusText);
                }
            });

        }

        function fnGetAllDepartment() {
            $.ajax({
                url: '/Employee/GetAllDepartment',
                type: "POST",
                contentType: "application/json; charset=utf-8",
                success: function (response) {
                    $('#drpDeptName').empty().append('<option selected="selected" value="0">Select Department</option>');
                    $.each(response, function (key, value) {
                        $("#drpDeptName").append($("<option></option>").val(value.Id).html(value.Name));
                    });
                },
                error: function (err) {
                    alert(err.statusText);
                }
            });
        }



</script>

EmployeeManagmentSystem/Views/Employee/Index.cshtml
@model List<Model.Employee>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MasterPage.cshtml";
}


<div class="container">

    <div class="row pull-right">
        <a href="@Url.Action("Add", "Employee")" class="btn btn-warning">Add Record</a>
    </div>
    <div class="row" style="margin-top: 50px;">
        <table class="table table-bordered table-responsive">
            <thead>
                <tr>
                    <th>Department Name</th>
                    <th>Name</th>
                    <th>SurName</th>
                    <th>Qualification</th>
                    <th style="text-align: center">Contact Number</th>
                    <th>Address</th>

                    <th style="text-align: center;">Edit</th>
                    <th style="text-align: center;">Delete</th>
                </tr>
            </thead>
            <tbody>
                @if (Model != null)
                {
                    foreach (var item in Model)
                    {
                    <tr>
                        <td>@item.DepartmentName</td>
                        <td>@item.Name</td>
                        <td>@item.Surname</td>
                        <td>@item.Qualification</td>
                        <td style="text-align: center">@item.ContactNumber</td>

                        <td>@item.Address</td>

                        <td style="text-align: center;"><a href="@Url.Action("Add", "Employee", new { Id = @item.Id })"><i class="fa fa-pencil"></i></a></td>
                        <td style="text-align: center;"><a href="#" onclick="fnDeleteById(@item.Id)"><i class="fa fa-trash" aria-hidden="true"></i></a></td>

                    </tr>
                    }
                }
                else
                {
                    <tr>
                        <td colspan="6" style="text-align: center;">No Data Available</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>


<script>
    $(document).ready(function () {
       

    });

    function fnDeleteById(id) {

        if (confirm("Do you want to delete this record?")) {
            $.ajax({
                url: '/Employee/Delete',
                type: "POST",
                contentType: "application/json; charset=utf-8",

                data: "{'empId': '" + id + "'}",
                success: function (result) {
                    if (result == "Ok") {
                        window.location.href = "@Url.Action("Index", "Employee")"
                        }
                    },
                    error: function (err) {
                        alert(err.statusText);
                    }
                });
            }

        }
</script>

EmployeeManagmentSystem/Views/Employee/Save.cshtml
@{
    ViewBag.Title = "Save";
    Layout = "~/Views/Shared/_MasterPage.cshtml";
}

<h2>Save</h2>

EmployeeManagmentSystem/Views/Shared/_MasterPage.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Employee Managment System</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <style>
        .navbar-inverse .navbar-nav>li>a {
    color: white !important;
    font-weight:bold;
}
    </style>
  <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <ul class="nav navbar-nav">
                <li><a href="@Url.Action("Index","Department")">Department</a></li>
                <li><a href="@Url.Action("Index","Employee")">Employee</a></li>
            </ul>
        </div>
    </nav>
</head>
<body>
    <div>
        @RenderBody()
    </div>
</body>
</html>